### PR TITLE
Make navbar sticky

### LINKED ISSUE #331: Keep Navigation bar stuck to the top even while scrolling
### Description
While scrolling the page, it'll be nice if the navigation bar sticks to the top. I have been constantly switching between light and dark theme based on the time of the day. If I'm at a problem somewhere in the latter half of the page, I have to scroll back to the top to toggle the theme and then scroll back down. This back and forth can be minimized by making the navigation bar stick to the top of the page.
Here is a pull request for the proposed fix: #332

I hope this feature can help others as well.

#### When at the top of the page
image

#### When not at the top of the page
image

### PR DESCRIPTION
**Pull request by sinharaksh1t**
Resolves #331

#### Before
leetcode patterns before

#### After
leetcode patterns after

### CODE REVIEW

**Review by seanprashad — APPROVED** [review]
Appreciate you opening a PR for this @sinharaksh1t! Everything looks good to me 👍🏽

**Comment by sinharaksh1t** [comment]
Thank you for the quick merge, @seanprashad!

I'm curious what is the CI/CD pipeline like? Do the changes in `main` branch get auto deployed or do you do it manually?

**Comment by seanprashad** [comment]
They currently don't get autodeployed via the `github-pages` GitHub Action - this is something I should definitely look into because I remember it was working previously.

I've just manually kicked off a deployment - you should see the changes reflected in ~10 minutes or so!

**Comment by sinharaksh1t** [comment]
Wonderful, thanks a lot! :D

**Pull request merged**
