### PR TITLE
add padding to company icons

### LINKED ISSUE #114: Company icons are compacted
Screenshot 2021-09-02 103245

### PR DESCRIPTION
**Pull request by shreyshreyansh**
Fixes #114 

Before

Screenshot 2021-09-02 103245

After

Screenshot 2021-09-02 103219

### CODE REVIEW

**Review by seanprashad — CHANGES_REQUESTED** [review]
Thanks for this @shreyshreyansh! I'd love to merge this in but in order to do so, we'll need to revert the changes to `package-lock.json` since this patch should only contain the CSS changes.

Feel free to make that update and we'll be good to go! 🙌🏽

**Comment by shreyshreyansh** [comment]
Ok I will do the changes

**Comment by seanprashad** [comment]
Great! If you have any troubles removing it, the following command should be what we're looking for:

```sh
git checkout master package-lock.json
```

Then just create a new commit, push it to your existing branch, and I'll take a look!

**Comment by seanprashad** [comment]
Great! If you have any trouble removing it, the following command should be what we're looking for:

```sh
git checkout master package-lock.json
```

Then just create a new commit, push it to your existing branch, and I'll take a look!

**Pull request closed without merging**
