### PR TITLE
This question doesn't really utilize topological sorting in the tradi…

### PR DESCRIPTION
**Pull request by Omarfos**
…tional sense, I would suggest removing this tag

### CODE REVIEW

**Comment by SeanPrashad** [comment]
Hey @Omarfos - thanks for the PR!

[Here's a top-voted topological sort solution](https://leetcode.com/problems/minimum-height-trees/discuss/76129/Share-my-BFS-JAVA-code-using-degree-with-explanation-which-beats-more-than-95) from what I see in the discuss section:

```java
List<List<Integer>> myGraph = new ArrayList<List<Integer>>();
	List<Integer> res = new ArrayList<Integer>();
	if (n==1) {
		res.add(0);
		return res;
	}
    int[] degree = new int[n];
    for(int i=0; i<n; i++) {
    	myGraph.add(new ArrayList<Integer>());
    }
    for(int i=0; i<edges.length; i++) {
    	myGraph.get(edges[i][0]).add(edges[i][1]);
    	myGraph.get(edges[i][1]).add(edges[i][0]);
    	degree[edges[i][0]]++;
    	degree[edges[i][1]]++;
    }
    Queue<Integer> myQueue = new ArrayDeque<Integer>();
    
    for(int i=0; i<n; i++) 
    	if (degree[i]==0) 
    		return res;
    	else if (degree[i]==1) {
    		myQueue.offer(i);
    	}
    
    while (!myQueue.isEmpty()) {
    	res = new ArrayList<Integer>();
    	int count = myQueue.size();
    	
    	for(int i=0; i<count; i++){
    		int curr = myQueue.poll();
    		res.add(curr);
    		degree[curr]--;
    		for(int k=0; k<myGraph.get(curr).size(); k++) {
    			int next = myGraph.get(curr).get(k);
    			if (degree[next]==0) continue;
    			if (degree[next]==2) {
    				myQueue.offer(next);
    			}
				degree[next]--;
    		}
    	}      	
    }
    return res;
```

To me, this looks like the normal setup and execution of topological sort - build a graph; create an indegree array; add all leaf nodes (indegree of 1) to a Queue and then process it by decrementing each of its neighbours indegree, and adding it to the Queue if the indegree is 1.

I'd love to hear your thoughts on this! Ty!!

**Comment by Omarfos** [comment]
Hi @SeanPrashad, topological sorting using bfs works here, but not the one with dfs. In addition, there's several ways to solve this such as finding the longest path in the graph and etc. Topological sorting usually deals with having a node be before another node/ fulfilling dependencies. But I would suggest leaving this problem there because I learned how to topological sort with bfs from it. Maybe add this problem [https://leetcode.com/problems/sort-items-by-groups-respecting-dependencies/](https://leetcode.com/problems/sort-items-by-groups-respecting-dependencies/).

**Comment by SeanPrashad** [comment]
Thanks for following up @Omarfos! I definitely agree that this question, and many others, have multiple solutions but I haven't added tags for every single possibility (it is possible but time consuming).

I also definitely agree with you that Topological sort via BFS works here but I think it also works for DFS - [see this solution](https://leetcode.com/problems/minimum-height-trees/discuss/573561/Fast-and-Simple-recursive-JAVA-solution-with-Explanation) (please share your own solution if this isn't what you mean!).

I'm happy to add the `sort-items-by-groups-respecting-dependencies` question - I haven't solved it before but skimming through the [Discuss section](https://leetcode.com/problems/sort-items-by-groups-respecting-dependencies/discuss/?currentPage=1&orderBy=most_votes&query=), it looks promising!

How do you feel about adjusting this PR to add the question you suggested? Here's the companies who have asked it recently:

image

**Comment by Omarfos** [comment]
Hi @SeanPrashad, thank you for the quick responses. What I meant to say is that [Topological Sorting](https://en.wikipedia.org/wiki/Topological_sorting) is supposed to be used on DAGs. The solution you linked uses recursion(dfs), but the graph is undirected. Regardless, I think leaving the topological sort tag is good.

I've committed the problem. I'm a git noob, so I'm not sure if the pull request was updated

**Pull request merged**
